import ctypes

print('running')
cohr_dll = ctypes.cdll.LoadLibrary(
"C:/Users/Light-saver/Documents/LabVIEW/Lasers/Coherent Genesis/Win64/CohrHOPS.dll")
v0 = ctypes.create_string_buffer(16)
ret = cohr_dll.CohrHOPS_GetDLLVersion(v0)
# print(str(v0.value))
v1 = (ctypes.c_ulonglong * 2)()  # (ctypes.c_ulonglong * 2)()
v2 = ctypes.c_ushort()
v2p = ctypes.pointer(v2)
v3 = ctypes.c_ushort()
v3p = ctypes.pointer(v3)
v4 = ctypes.c_ushort()
v4p = ctypes.pointer(v4)
v5 = ctypes.c_ushort()
v5p = ctypes.pointer(v5)
v6 = ctypes.c_ushort()
v6p = ctypes.pointer(v6)
v2p = ctypes.create_string_buffer(16)  # wintypes.LPDWORD()
v3p = ctypes.create_string_buffer(16)  # wintypes.LPDWORD()
v4p = ctypes.create_string_buffer(16)  # wintypes.LPDWORD()
v5p = ctypes.create_string_buffer(16)  # wintypes.LPDWORD()
v6p = ctypes.create_string_buffer(16)  # wintypes.LPDWORD()
ret = cohr_dll.CohrHOPS_CheckForDevices(v1, v2p, v3p, v4p, v5p, v6p)

ret = cohr_dll.CohrHOPS_InitializeHandle.argtypes = [ctypes.c_ulonglong, ctypes.c_void_p]
v7 = ctypes.create_string_buffer(16)
ret = cohr_dll.CohrHOPS_InitializeHandle(v1[0], v7)
ret = cohr_dll.CohrHOPS_SendCommand.argtypes = [ctypes.c_ulonglong, ctypes.c_void_p, ctypes.c_void_p]
v8p = ctypes.create_string_buffer(16)
v11p = ctypes.c_char_p(b'PCMD=50')
ret = cohr_dll.CohrHOPS_SendCommand(v1[0], v11p, v8p)
# time.sleep(3)
v10p = ctypes.c_char_p(b'KSWCMD=1')
v12p = ctypes.create_string_buffer(16)
ret = cohr_dll.CohrHOPS_SendCommand(v1[0], v10p, v12p)
cohr_dll.CohrHOPS_Close.argtypes = [ctypes.c_ulonglong]
ret = cohr_dll.CohrHOPS_Close(v1[0])
print('closed')
print(ret)
